### ISSUE TITLE
create docs

### ISSUE THREAD

**Issue by aaronzshey** [aaronzshey/react-hexgrid#31]
I'm done with working on stories, and we don't have ANY documentation.  time to fix that.  (how did this package get to 55k with no docs?)

**Comment by aaronzshey** [comment]
Docs outline:

**-- Getting Started** 
 -  Your First App 
 - Using Generators
 - Using Layout
 - Using Path
 - Using Patterns
 - Dragging And Dropping

**-- API Documentation**
 - Types (folder) 
 -   > Hex,
 -   > Orientation
 -   > Point
 - Components (folder) 
 -   > Hexagon
 -   > HexGrid
 -   > Generator
 -   > Layout 
 -   > Path
 -   > Pattern

**Comment by aaronzshey** [comment]
For types like Hex, Orientation, and Point, we will use TypeDoc:
https://github.com/storybookjs/storybook/discussions/17646

**Comment by aaronzshey** [comment]
event functions such as onMouseEnter allow arguments onMouseEnter(e, {data, state, props{).  these can be used instead of this to access hexagon information.

**Comment by aaronzshey** [comment]
ondrag handlers are implemented on the g tag because g supports on drag but not polygon. 
https://svgwg.org/svg2-draft/struct.html#GElement -> global attributes include on drag

**Comment by aaronzshey** [comment]
adding 

```css

[draggable] {
    -moz-user-select: none;
    -khtml-user-select: none;
    -webkit-user-select: none;
    user-select: none;
    -moz-user-drag: element;
    -webkit-user-drag: element;
    -khtml-user-drag: element;
    user-drag: element;
}
```

to index.css and then referencing index.css from App.tsx can make on drag start working
